### ISSUE TITLE
Idea: Add Prompts between Prompts

### ISSUE THREAD

**Issue by Ashdevz** [rewbs/sd-parseq#103]
Be good to add new prompts between  prompts, rather than copy and pasting all +/- prompts and moving them down manually to insert a new prompt.

Will certainly buy you another coffee!

**Comment by sashaagafonoff** [comment]
if i'm doing bulk edits, i will use the following worklfow: 

1. download the parseq file and open in text editor
2. remove generated frames section
3. edit JSON directly
4. load as new document (it works very well provided you deleted generated frames)

[optional] 

1. copy relevant JSON (prompts, frames) into JSON to CSV converter (e.g. [https://codebeautify.org/json-to-csv#](https://codebeautify.org/json-to-csv#))  
2. edit numbers/text/order/etc in spreadsheet of preference
3. convert CSV back to JSON
5. paste updated JSON back into your master JSON file (with generated section deleted)
6. load as new doc

hope that helps - I can do a video or screenshots if that helps - and this solves a number of edits which aren't supported with bulk edit

**Comment by rewbs** [comment]
Thanks both! This is a good idea. Meanwhile, in addition to the workaround @sashaagafonoff suggested, note that the order in which prompts are used in the time line does not have to match their order in the list. So you can add a prompt at the end of the list and schedule it first or in the middle.

This makes me wonder: would you prefer it if the prompts in the list automatically re-ordered to match the order of their starting frames? If that satisfies your use case, it could remove the need to insert new prompts between others.

**Comment by Ashdevz** [comment]
Yes reordering the sequential prompt numbers automatically based on the frame sections would be an even better idea!
