### ISSUE TITLE
Feature Idea: mark audio events by tapping a key while audio is playing

### ISSUE THREAD

**Issue by Djphill2003** [rewbs/sd-parseq#120]
I think it would be useful to have an event creator that is created by tapping the space bar while playing the track. For example, in a complex song, I could push play and then tap the space bar to match the kick drum beat.

**Comment by rewbs** [comment]
Hi! Thanks for the feature request. This is a good idea. The main challenge will be to implement it in a way that is sufficiently accurate.

**Comment by conorluddy** [comment]
That's a cool idea 👍🏼

**Comment by rewbs** [comment]
This is in progress under https://github.com/rewbs/sd-parseq/compare/hotkeys?expand=1.

**Comment by rewbs** [comment]
This is now live. Hit shift-a during playback to add a marker. Let me know whether it's sufficiently accurate.

**Comment by Djphill2003** [comment]
Awesome! Thanks! I played with it tonight and it made the process a lot easier.

—Dan—
