### ISSUE TITLE
Suggestion: checkbox to toggle common prompt prepend/append mode

### ISSUE THREAD

**Issue by Baldoak-sd** [rewbs/sd-parseq#159]
Hello,

Thanks for creating such a fantastic tool. I really have a lot of fun using it and learning about all the different functions you've packed in.

I think it would be nice to have an option to toggle the position of the common prompt when prompts are combined for output; in other words, I think it could be useful to have a checkbox next to the common prompt section that would place your common prompt at the front of the combined prompt instead of at the end.

The reason I think this would be a good idea is two fold: First, because Stable Diffusion places greater emphasis on prompt items that are closer to the front of your prompt, and second, because I find that I typically put quality descriptors (masterpiece, hires, HDR, etc) at the front of my prompts and quality descriptors are a common prompt element between most of my prompts.

Hope this isn't too much of a corner use case, and wishing you the best of luck in all of your endeavors! Keep up the great work 👍👍👍

**Comment by rewbs** [comment]
In progress in branch https://github.com/rewbs/sd-parseq/tree/extra-functions-info

**Comment by rewbs** [comment]
This is now deployed to prod.
