### ISSUE TITLE
Feature request: Math within a cell

### ISSUE THREAD

**Issue by KewkLW** [rewbs/sd-parseq#162]
This functionality is just a quality of life improvement. Something I use in Blender all the time. Which is doing math within a cell. Say my seed is 1234 and I want to get to a specific number. If I input 1234+100 then hit enter it would do the math and the input would change to 1334.

**Comment by rewbs** [comment]
Good idea. Here's a quick implementation that allows maths expressions in the value columns: https://sd-parseq--dev-feiki1ng.web.app/ . (It seems to have broken quickly clearing a value from a cell without bringing up the editor though, so not merging yet...)

**Comment by rewbs** [comment]
This is now deployed to prod.
