### ISSUE TITLE
Feature Request: Control CFG scale

### ISSUE THREAD

**Issue by shihanqu** [rewbs/sd-parseq#164]
Would great of Parseq could manage the CFG scale schedule. In many situations, CFG is just as important as controlling strength!

**Comment by rewbs** [comment]
Hi! CFG scale is already available as `scale`. Sorry if this is confusing.

**Comment by shihanqu** [comment]
Thank you. I would only recommend adding the words "CFG" in the Readme somewhere for people who ctrl+f search for it. Cheers
