### ISSUE TITLE
Feature Request: "final_keyframe" context variable

### ISSUE THREAD

**Issue by shihanqu** [rewbs/sd-parseq#165]
As the title says, it would be great to have a "final_keyframe" context variable, that is equivalent to the "max_f" variable in deforum. Just as the "active_keyframe" variable returns the current frame number, "final_keyframe" would return the same number entered in the Final frame field.

**Comment by rewbs** [comment]
Good idea. This is under development now.

**Comment by rewbs** [comment]
This is now deployed as the `last_keyframe` context variable.

**Comment by shihanqu** [comment]
Great stuff! Would recommend updating https://github.com/rewbs/sd-parseq/blob/master/README.md#context-variables to include this
