### ISSUE TITLE
If not a bug, feature request. 

### ISSUE THREAD

**Issue by KewkLW** [rewbs/sd-parseq#167]
This may be a "me" problem lol but I would love to be able to select all the cells with frames and delete them all at once :D 
![image](https://github.com/rewbs/sd-parseq/assets/57611539/9a59fa09-67ea-4dc3-9c7b-11836b9cfd89)

**Comment by rewbs** [comment]
What you can do is drag on any column except the frame number to select a range of row, and then when you open the delete dialog, those frames will be pre-populated for deletion:

<img width="580" alt="image" src="https://github.com/rewbs/sd-parseq/assets/74455/43454a98-8678-4ed7-abac-5b2b180ec9de">

<img width="925" alt="image" src="https://github.com/rewbs/sd-parseq/assets/74455/7f2d29e9-5121-4da1-a2be-fa8c69c0b6df">

Is that good enough or are you after something else?

**Comment by KewkLW** [comment]
Oh hell yeah! :)
