### ISSUE TITLE
TimeSeries Slider & Play button not working

### ISSUE THREAD

**Issue by SHaringT** [rewbs/sd-parseq#189]
Hi,

I tried to use the web app to make a manifest. When I load a soundfile into the create timeseries ui and extract the amplitude/pitch I just can see the start. I can't move the blue slider to select another timeframe to be shown. Sometimes it moves but jumps right back.

Also the play button is not working. It shows "Pause" for a blink of an eye and then is back to play.

Tried it with Brave & Chrome browser.

Can I add further information? Would be glad to find a solution

Greetings

**Comment by rewbs** [comment]
Thanks for the report, you're absolutely right. Fixing now, hold tight.

**Comment by rewbs** [comment]
This is resolved in v0.1.94, which is now deployed. Thanks again for the report and apologies for the issue!

**Comment by SHaringT** [comment]
Thanks for resolving it so quickly! Just an additional question if that is okay here: Is it intended to only update the positon when extracting once more? If not I could also try to take a look.

Greetings

**Comment by rewbs** [comment]
Hi! Yes that is my intent: only the selected segment is analysed, so if you select another segment you have to reanalyze, aka extract.

The alternative would be to analyse the whole track upfront and store the result in memory, and then allow the user to pan along the full analysed segment. I worry this would be too slow on long audio files.

So I have a slight preference for keeping the functionality as is. That being said I agree the UX is not very clear so if you have any ideas to make it more intuitive that would be awesome.

**Comment by SHaringT** [comment]
Relatable. Do you have an Idea of where the perfomance bottleneck is? I only slightly touched JS/React and no typescript at all. From a Python/C# perspective the information and processing amount seems to be manageable. From The usage it seems like UI perfomance is falling behind?

I'm not trying to speak down your code, It's a great piece I just merely dipped into using and am quite interested in, not just from the user perspective. I just took a few glimpses into the code, but as the computing is done locally anyways maybe it would be an idea to outsorce the saving and processing to another backend/process/mini-api-server so the UI may just do it's UI thing? Apologies if something like this already is happening. 

For the intuitiveness part; Maybe rename the button to "process snippet" and/or put an explanation next to it that only this part is processed? I need to say I'm also a madman at things like that and just skip through documentations when something is not working and gradually test through UI's :D Maybe also adding "calculation range from ms x to ms y" input box so everyone can test which range is still working good and you don't need to cut the piece in audacity to create seamless processed snippets.

Thanks for being so responsive and greetings!
