### ISSUE TITLE
Dark Mode: Bulk Edit Keyframes Font

### ISSUE THREAD

**Issue by sashaagafonoff** [rewbs/sd-parseq#197]
The confirmation text is hard to read in dark mode:
<img width="674" alt="image" src="https://github.com/rewbs/sd-parseq/assets/100696/0c8e6372-7f85-4778-9a5f-2579282a26f0">

**Comment by rewbs** [comment]
Well spotted, thank you!

**Comment by rewbs** [comment]
This is now fixed. Thanks again!
