### ISSUE TITLE
Feature Request: Add offset to event detection

### ISSUE THREAD

**Issue by KewkLW** [rewbs/sd-parseq#220]
I'm not sure (yet) this will really make much of a difference in terms of animation sync but wanted to throw it up just in case. As you can see from the screenshot, the Energy algo is catching all transients and not adding anything extra. But it's offset across all markers by about 50ms or so. It seems to be even so a global offset would or should line them all up. 

![image](https://github.com/rewbs/sd-parseq/assets/57611539/b217ebaa-5454-462f-8e7b-4d96360728ef)

**Comment by rewbs** [comment]
Agreed, I've run into this before and I can see how it would be useful.

**Comment by rewbs** [comment]
Ready for testing under https://github.com/rewbs/sd-parseq/pull/225.

**Comment by rewbs** [comment]
This is now live as of v0.1.111.
