### ISSUE TITLE
Allow scheduling of noise multiplier in Parseq

### ISSUE THREAD

**Issue by andyxr** [rewbs/sd-parseq#221]
I think today we allow noise to be scheduled, but not noise _multiplier_. Would be a great addition, as the multiplier is becoming a key aspect of XL-based animations.

**Comment by rewbs** [comment]
Done under https://github.com/rewbs/sd-parseq/pull/223 – releasing to prod shortly.

**Comment by rewbs** [comment]
Live in prod from v0.1.106.
