### ISSUE TITLE
new to parseq

### ISSUE THREAD

**Issue by andysingal** [rewbs/sd-parseq#222]
Tried to create animation as mention in your video: https://www.youtube.com/watch?v=MXRjTOE2v64. Love to understand what i am doing wrong: 

https://github.com/rewbs/sd-parseq/assets/20493493/0fe5c361-444c-400e-8620-02de2dddbe0f

- https://github.com/rewbs/sd-parseq/assets/20493493/a01d71f5-41a6-4706-ae8e-40b2f75f44ae
-  **using sdxl-base  model for creating image but not getting any consistency** 

<img width="1821" alt="Screenshot 2023-10-09 at 1 32 02 PM" src="https://github.com/rewbs/sd-parseq/assets/20493493/fa86ac40-cd3e-4bb9-b7ee-972d4976d29c">
<img width="1830" alt="Screenshot 2023-10-09 at 1 32 28 PM" src="https://github.com/rewbs/sd-parseq/assets/20493493/aad32d98-71b9-444b-919b-e8fb6e4676b2">
<img width="1774" alt="Screenshot 2023-10-09 at 1 32 53 PM" src="https://github.com/rewbs/sd-parseq/assets/20493493/3a1cde2b-3087-4981-87f4-f12aa71b6f82">

![image (1)](https://github.com/rewbs/sd-parseq/assets/20493493/716d30dc-439c-442d-95fe-8bc83f1fe386)

**Comment by rewbs** [comment]
I'm closing this because it looks like you got the help you needed [over on discord](https://discord.com/channels/1011314943380959313/1063254461960691792/1160990181978030151). Feel free to re-open if you need more input.
