### ISSUE TITLE
"no such file or directory" downsample/index.js.map

### ISSUE THREAD

**Issue by bobdobbs** [rewbs/sd-parseq#228]
When I edit the 'final frame' field, the browser pane whitescreens.

At the terminal I get this message: 

```
WARNING in ./node_modules/downsample/index.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/home/mantis/opt/sd-parseq/node_modules/downsample/index.js.map' file: Error: ENOENT: no such file or directory, open '/home/mantis/opt/sd-parseq/node_modules/downsample/index.js.map'
```

If I look in that directory, I can see that indeed the file 'index.js.map' does not exist.
The file 'index.js' in the same directory does exist.

The last error message in the browser console:
Uncaught TypeError: Cannot read properties of undefined (reading 'prompt_weight_1')

**Comment by rewbs** [comment]
Thanks for the report. Is this on the staging version of Parseq?

**Comment by rewbs** [comment]
If it was staging, I have just pushed a new version which I think fixes the issue. Let me know how you go.

**Comment by bobdobbs** [comment]
Hey @rewbs.

I was getting this behaviour in master.

But after updating from master today, I no longer get this behaviour.

Thank you.
