### ISSUE TITLE
parsec section not showing up in deforum

### ISSUE THREAD

**Issue by WilsonKingpin** [rewbs/sd-parseq#45]
hey there, I did every step with installing this parseq script but it doesn't show up below in keyframes by deforum.

after doing the steps I have closed the webui multiple times

**Comment by rewbs** [comment]
Hi! So the parseq python script is deprecated, you don't need to do anything with that. It was basically an inferior equivalent of deforum and I've stopped working on it.

What you need to do is make sure that the deforum extension code you've put in the A1111 extensions directory is the correct branch. Until the parseq integration functionality is merged into the main repo, you'll need to run this in your A1111 extensions directory (after removing any prior deforum extension).

```
git clone https://github.com/rewbs/deforum-for-automatic1111-webui.git deforum
cd deforum
git checkout parseq-integration
```

**Comment by enzyme69** [comment]
Missing step on the front page documentation:
```
% git clone https://github.com/rewbs/deforum-for-automatic1111-webui.git
git checkout parseq-integration
Cloning into 'deforum-for-automatic1111-webui'...
remote: Enumerating objects: 3246, done.
remote: Counting objects: 100% (808/808), done.
remote: Compressing objects: 100% (150/150), done.
remote: Total 3246 (delta 711), reused 735 (delta 658), pack-reused 2438
Receiving objects: 100% (3246/3246), 71.97 MiB | 10.82 MiB/s, done.
Resolving deltas: 100% (1925/1925), done.
error: pathspec 'parseq-integration' did not match any file(s) known to git
```

**Comment by rewbs** [comment]
As of yesterday, you no longer need to use my branch of the Deforum extension for automatic1111. You can just install the latest version of the official extension and the parseq input field will be available. I have updated the README accordingly.

I'm closing this issue, please let me know if you still have any concerns.
