### ISSUE TITLE
Analyze Song feature

### ISSUE THREAD

**Issue by Flonixcorn** [rewbs/sd-parseq#50]
A feature that auto analises a mp3 or wav file you give it, or an easier way to create sound matching keyframes

**Comment by rexorp** [comment]
That would be a great feature to implement.
There are apps that do that like this one: https://www.chigozie.co.uk/audio-keyframe-generator/
Maybe this code could be implement in to it.

**Comment by rewbs** [comment]
Coming soon, see: https://github.com/rewbs/sd-parseq/pull/54

**Comment by rewbs** [comment]
Closing as this has been released and has proved stable ([see "audio analyser" section in readme](https://github.com/rewbs/sd-parseq#audio-analyser-for-automatic-keyframe-creation-from-audio-data)). Please raise any improvement requests as separate issues.
