### ISSUE TITLE
AttributeError: 'ParseqAnimKeys' object has no attribute 'kernel_schedule_series'

### ISSUE THREAD

**Issue by cibernicola** [rewbs/sd-parseq#52]
I am testing (congratulations for the work), for the moment only the execution of the "demo" in https://sd-parseq.web.app/?docId=doc-f9bbde46-fd5a-4c03-84b5-fb20efd7ae20, in Automattic webUI. I copy the generated json and paste it in the indicated place. When I hit generate I get the following error:

`AttributeError: 'ParseqAnimKeys' object has no attribute 'kernel_schedule_series'`

I don't know if I am forgetting some parameter or I am doing something wrong or it is some kind of error.

PS: The default animation in the extension runs correctly, I insist, without touching any configuration.

Thanks, and again great work!

**Comment by rewbs** [comment]
Hi! Thanks for the report. Could you please attach the full log output from Automaic1111?

**Comment by rewbs** [comment]
Actually I can see some new schedules were added in the extension under https://github.com/deforum-art/deforum-for-automatic1111-webui/pull/159/files .

I will update Parseq shortly to support those and find a way to avoid failures when new ones are added.

**Comment by rewbs** [comment]
There is a fix in this branch of the A1111 deforum extension (currently under PR): https://github.com/rewbs/deforum-for-automatic1111-webui/tree/fix-parseq-with-antiblur-or-new-params . This fix ensures the extension tolerates the case where the Deforum extension is trying to use parameters that aren't defined in the Parseq manifest (and will fall back to the standard Deforum animation series).

I will also update the Parseq UI to support the 4 new parameters for anti-blur.

**Comment by cibernicola** [comment]
> There is a fix in this branch of the A1111 deforum extension (currently under PR): https://github.com/rewbs/deforum-for-automatic1111-webui/tree/fix-parseq-with-antiblur-or-new-params . This fix ensures the extension tolerates the case where the Deforum extension is trying to use parameters that aren't defined in the Parseq manifest (and will fall back to the standard Deforum animation series).
> 
> I will also update the Parseq UI to support the 4 new parameters for anti-blur.

Tested, fully working now, thanks!
