### ISSUE TITLE
[Feature request] Use Parseq only for keyframe animations

### ISSUE THREAD

**Issue by bachagabriel** [rewbs/sd-parseq#56]
Parseq currently overwrites most Deforum settings. It is very powerful for keyframe animations but it would be good to have the possibility to keep using all other deforum settings and only use parseq for camera movements.

**Comment by michaelevy804** [comment]
Would like to second this- I think it would be ideal if parseq just defaulted to not overriding anything and there were a menu where you could tick off all the things that you do want it to override- independent of the show fields menu but formatted the same way

**Comment by rewbs** [comment]
This is implemented in https://github.com/rewbs/sd-parseq/pull/74 , which will be released to [sd-parseq.web.app](https://sd-parseq.web.app/) soon – (meanwhile you can try it on https://sd-parseq--staging-bu53tr5b.web.app ).

Note that this is dependent on a change to the Deforum extension which is pending here: https://github.com/deforum-art/deforum-for-automatic1111-webui/pull/408

<img width="1885" alt="image" src="https://user-images.githubusercontent.com/74455/222324141-de2d3d68-de03-4ad1-ae2e-e3c4c0de191f.png">
