### ISSUE TITLE
Can't render keyframes/Vis Param flow not showing

### ISSUE THREAD

**Issue by FizzleDorf** [rewbs/sd-parseq#57]
Hey Rewbs, I've tried to render out some keyframes but I am perpetually stuck with "Please render to update the output" in the output no matter what. There is no error being thrown and I tried locally just in case, same issue. Since I can't render I haven't been able to see the visualized parameter flow either. The sparklines, when selected, just whites out the screen. Let me know if there is anything else you need to know. Thanks.

![Capture](https://user-images.githubusercontent.com/46942135/214354944-62c7b109-3fa2-4213-a306-e5e7b7b256ab.JPG)

**Comment by rewbs** [comment]
Ah damn, I saw this once before during development. I couldn't figure out the root cause and then could no longer recreate it. It just seemed like a bunch of react components didn't render at all. Are you seeing this consistently? What about with a fresh browser session? Any errors in the JavaScript console?

**Comment by FizzleDorf** [comment]
Seems to be working now. Very strange. I wish I would have found some clue as to what was going on. It was behaving the same way until I hosted locally. 
![Capture](https://user-images.githubusercontent.com/46942135/214758700-72e8c180-eeb3-4245-a26a-15ab36b92b80.JPG)

**Comment by FizzleDorf** [comment]
Weird, it wasn't working in a web session but is working just fine now after trying to run locally. I wish I could have offered more insight to the cause. I don't remember getting an Error in the JS console and I'm sure I've checked when I was having issues. Thanks for the help. 

![Capture](https://user-images.githubusercontent.com/46942135/214759046-6676a41a-b9a2-4105-a0ef-0c2a912941f1.JPG)

**Comment by FizzleDorf** [comment]
Hey rewbs, I wanted to do some tests with controlnet and Parseq but I'm not able to render out the vis param flow. This time I am getting the error:

    sortedKeyframes.findLast is not a function

in the browser version it's:

    i.findLast is not a function

Nothing else is displayed in my Conda terminal when use it locally. Any ideas for a fix?

**Comment by rewbs** [comment]
Hi, what browser are you using? findLast is a JavaScript function on arrays that was added relatively recently (in the last 6-12 months on most browsers): https://caniuse.com/?search=findLast .

**Comment by FizzleDorf** [comment]
I'm using Firefox.

**Comment by FizzleDorf** [comment]
can confirm it's working on Brave. All good.
