### ISSUE TITLE
Issues with doing lots of prompts

### ISSUE THREAD

**Issue by michaelevy804** [rewbs/sd-parseq#60]
Scheduling a ton of prompt changes leads to the parseq gui crashing to error code: out of memory

**Comment by darkflare** [comment]
![image](https://user-images.githubusercontent.com/1476298/218886844-a59db6a9-1676-4e3e-8287-7a1a253a6199.png)
Yes the same problem here! It hangs the browser... tried in all of them, it crashes everyone.

**Comment by rewbs** [comment]
I believe this is resolved with the new prompt UI. If you still have issues with many prompts please re open.
