### ISSUE TITLE
Generated URL seems to change every upload 

### ISSUE THREAD

**Issue by sashaagafonoff** [rewbs/sd-parseq#82]
Is the generated URL meant to change each time? I'm finding that the file I'm working on at the moment seems to change on every upload event, so i need to make sure that the manifest URL in Deforum GUI is updated each time I make changes... I am pretty sure it was maintaining the same URL upload to upload for a single document in the past...

**Comment by rewbs** [comment]
Hi! The token in changes after every upload but the prior url should continue to work and point to the new content. In other words, yes you can get a new URL after every upload if you like, but you can ignore that and just keep using the first one, and you should be fine.

If that's not the case for you, could you supply some example URLs for the same document that don't show the latest content?
