### ISSUE TITLE
Unable to increase frame count beyond 119

### ISSUE THREAD

**Issue by motivix** [rewbs/sd-parseq#90]

**Comment by rewbs** [comment]
You can change the frame count to any number by editing the frame number of the final keyframe. Let me know how it goes.

**Comment by im-stuff** [comment]
> You can change the frame count to any number by editing the frame number of the final keyframe. Let me know how it goes.

This does not work for me either. If you try to write in a value over 119 it sets it back to 119.

**Comment by rewbs** [comment]
Hi, I cannot recreate this. Can you confirm you are editing the frame number in the keyframe grid and not the prompt section? Can you attach a screen cap or screenshot to show more specifically what you're trying?

**Comment by rewbs** [comment]
Great thanks for letting me know! Closing this now.
