### ISSUE TITLE
Add keyboard shortcuts

### ISSUE THREAD

**Issue by rewbs** [rewbs/sd-parseq#96]
There are some keyboard shortcuts that work when the grid has focus (e.g. ctrl-a to add frame, ctrl-d to delete frame).

However, it would be good for these to work regardless of focus (assuming focus doesn't use that shortcut), and for more shortcuts to be added, including:
- start/stop reference audio (default: space)
- jump to prompts (default: ctrl-p)

Please comment with any other keyboard shortcuts you'd like to see.

**Comment by il-vanzo** [comment]
If possible, in the start/stop reference audio, another variation could be, instead of stopping, replay from the last pause (Ctrl-space perhaps?)

**Comment by rewbs** [comment]
Initial set of keyboard shortcuts are now enabled:

Undo/redo:
- `ctlr/cmd-z` to undo
- `shift-ctlr/cmd-z` to redo

Audio playback:
- `space` to play/pause audio reference
- `shift-space` to play audio reference from start
- `ctrl-space` to play audio reference from last pause position
- `shift-a` to add marker at current audio playback position.

**Comment by il-vanzo** [comment]
Nice!

**Comment by geodev** [comment]
Wonderful
